### ISSUE TITLE
getting 'missing authentication token' after installing awsm-users

### ISSUE THREAD

**Issue by whatsdis** [dekz/awsm-users#3]
I did a npm install awsm-users

deployed but when I tried to create a new user it says

`{"message":"Missing Authentication Token"}`

**Comment by dekz** [comment]
Are you hitting the `<lambda url>/users/create` endpoint? Or just `<lambda url>`?

**Comment by whatsdis** [comment]
@dekz yes. I put in my own end point....https://gshgasodhf83.execute-api.us-east-1.amazonaws.com/dev/users/create

**Comment by whatsdis** [comment]
@dekz  I checked aws_modules/ there is no users module so it wasn't installed when I ran `npm install awsm-users`

**Comment by dekz** [comment]
That's not great news, do you know which version of jaws you are executing this from?

**Comment by whatsdis** [comment]
@dekz 1.3.3

I used npm install because 
`jaws module install https://github.com/dekz/awsm-users`

Unsupported cmd install. Must be install|update|create

**Comment by dekz** [comment]
npm install is fine.

did you execute:

```
jaws postinstall awsm-users npm
```

In the jaws project directory?

**Comment by whatsdis** [comment]
no I did not.

**Comment by whatsdis** [comment]
> JAWS: -------------------------------------------
> JAWS:  Dashboard:  Deploying Endpoints...
> JAWS: -------------------------------------------
> JAWS: Endpoint Deployer:  Deploying endpoint(s) to region "us-east-1"...
> JAWS: Endpoint Deployer:  "dev - us-east-1": found 4 endpoints to deploy
> JAWS: Endpoint Deployer:  "dev - us-east-1": found existing REST API on AWS API Gateway with ID: g323g23g
> JAWS: Endpoint Deployer:  "dev - us-east-1": found 3 existing resources on API Gateway
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created resource: users
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created resource: authenticate
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created method: POST
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created integration with the type: AWS
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created new lambda access policy statement
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/authenticate": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created resource: create
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created method: POST
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created integration with the type: AWS
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created new lambda access policy statement
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/create": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created resource: list
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created method: GET
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created integration with the type: AWS
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created new lambda access policy statement
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - users/list": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created method: GET
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created integration with the type: AWS
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": removed existing lambda access policy statement
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created new lambda access policy statement
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created method response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created method integration response
> JAWS: Endpoint Deployer:  "dev - us-east-1 - greetings/hello": created method integration response
> JAWS: Endpoint Deployer:  Endpoints for stage "dev" successfully deployed to API Gateway in the region "us-east-1". Access them @ https://g3g3ggg.execute-api.us-east-1.amazonaws.com/dev/
> JAWS: -------------------------------------------
> JAWS:  Dashboard:  Deployments Completed
> JAWS: -------------------------------------------
> ssj@ss:/jaws/www# curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
>     "email": "higsg@sgs",
>     "password": "sgs"
> }' 'https://g32g32g32.execute-api.us-east-1.amazonaws.com/dev/users/create'
> {"errorMessage":"Missing required key 'TableName' in params","errorType":"MissingRequiredParameter","stackTrace":["fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:115:37)","validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:14)","validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:21)","validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:9:10)","Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:88:32)","Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)","/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:75:9","finish (/var/runtime/node_modules/aws-sdk/lib/config.js:236:7)","/var/runtime/node_modules/aws-sdk/lib/config.js:252:9","EnvironmentCredentials.get (/var/runtime/node_modules/aws-sdk/lib/credentials.js:126:7)","getAsyncCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:246:24)","Config.getCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:266:9)","Request.VALIDATE_CREDENTIALS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:70:26)","Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:101:18)","Request.emit (/var/runtime/node_modules/aws-    sdk/lib/sequential_executor.js:77:10)"]}

It seems to have deployed properly but the curl doesn't seem to work.

**Comment by dekz** [comment]
Take a look [here](https://github.com/dekz/awsm-users#environment-variables) for the environment variables that need to be set up.

At this stage, `USERS_TABLE` _must_ have the value `jaws-users`. Use the `jaws env set` command to set these environment variables.

**Comment by whatsdis** [comment]
@dekz 

`jaws env list` results in

error: missing required argument `stage'

update: oh that page explains it. thank you.

**Comment by dekz** [comment]
You're going to have to fill out the other arguments required by jaws as it is dependent on your project.

`jaws env list dev us-east-1` might be the correct choice of arguments for your situation.

**Comment by whatsdis** [comment]
@dekz got it. and use `jaws env set <stage> <region> <key> <val>` to set the variables right?

**Comment by whatsdis** [comment]
and what is the this 

JWT_SECRET=abcd
JWT_ISSUER=jacob

business? do I need to create some md5 hash?

**Comment by dekz** [comment]
This library issues JSON Web tokens for authentication.

A sufficiently long random ascii string should be fine. You do not have to md5 it.

**Comment by whatsdis** [comment]
@dekz the documnentation list example is missing 404 page. can you fix it I'm trying to figure out how to put my other jaws lambda end points behind the auth

**Comment by dekz** [comment]
When calling `authenticate` endpoint, you will be given a `jwt` token on a successful authentication.

This is then used as an `Authentication` HTTP Header on lambdas behind the auth wall.

[List users](https://github.com/dekz/awsm-users/blob/master/awsm/list/awsm.json#L33) is an example of a lambda behind the auth wall.

**Comment by whatsdis** [comment]
@dekz ah so after I create the module I just edit that part. Thank you for your help!

**Comment by dekz** [comment]
No worries, everything is moving quickly still and a little unstable.

Thanks for going through the steps and trying to get it working.

**Comment by whatsdis** [comment]
@dekz thank you. btw, is swagger editor compatible with jaws?

**Comment by dekz** [comment]
Not sure on the current sate of JAWS and Swagger, sorry.

**Comment by whatsdis** [comment]
no problem! it would be crazy tho
