### ISSUE TITLE
How to install it with serverless framework. 

### ISSUE THREAD

**Issue by medvedev-evgeny** [dekz/awsm-users#6]
The wiki explains how to install it in JAWS. What about serverless framework? I get an error when trying to perform this command: serverless postinstall awsm-users npm

> ServerlessError: In the command you just typed, the "postinstall" is valid but "awsm-users" is not.  Enter "serverless help" to see the actions for this context.

**Comment by marksteele** [comment]
ping

**Comment by medvedev-evgeny** [comment]
pong

**Comment by dekz** [comment]
This project only supports JAWS unfortunately. I may write a serverless version once Lambda is supported in more regions (mine).
